// src/pricing.js
//
// نظام تحديد الأسعار الخاص بكل مهنة على حدة.
//
// كل مهنة ليها "مخطط أسعار" (schema) فيه البنود اللي بيتحدد بيها سعر
// الشغلانة في المهنة دي: الصنايعي بيدخل سعر الوحدة لكل بند لما يسجل،
// والعميل بيدخل الكمية المطلوبة من كل بند وهو بيطلب — والسعر الكلي
// بيتحسب تلقائيًا: Σ (سعر الوحدة × الكمية).
//
// أمثلة:
//   - سيراميك: السعر بالمتر² للأرضيات والحوائط.
//   - محارة: محارة داخلية بسعر، ومحارة خارجية بسعر تاني.
//   - نقل اثاث: رفع بالدور + رحلة عربية + فك وتركيب غرف.
//   - سباك/كهربائي: ساعة عمل + بنود تانية حسب المهنة.
//
// المخطط بيتخزن هنا كمصدر واحد للحقيقة، وبيتوفر للتطبيق عبر
// GET /categories (pricing_items) عشان شاشتين التطبيق يتبنيوا ديناميكيًا:
//   1) صفحة أسعار الصنايعي بعد اختيار المهنة.
//   2) شاشة تفاصيل الطلب عند العميل.
//
// ملاحظة: المفتاح هو name_ar بتاع التصنيف زي ما هو متخزن في جدول
// categories (seed) في db.js — لو اتغير اسم تصنيف لازم يتغير هنا كمان.

const PRICING_SCHEMAS = {
  "سباك": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل (تركيبات وتصليحات)", unit_ar: "ساعة" },
      { key: "fixture_install", label_ar: "تركيب خلاط أو طباق", unit_ar: "قطعة" },
      { key: "leak_visit", label_ar: "كشف تسريب أو معاينة", unit_ar: "زيارة" },
      { key: "sink_install", label_ar: "تركيب حوض أو مغسلة", unit_ar: "قطعة" },
      { key: "wc_base_install", label_ar: "تركيب قاعدة حمام", unit_ar: "قطعة" },
      { key: "heater_install", label_ar: "تركيب سخان مياه", unit_ar: "قطعة" },
      { key: "pump_install_sp", label_ar: "تركيب موتور مياه", unit_ar: "قطعة" },
      { key: "float_install", label_ar: "تركيب عوامة خزان", unit_ar: "قطعة" },
      { key: "drain_snaking_sink", label_ar: "تسليك صرف حوض/حمام", unit_ar: "فتحة" },
      { key: "drain_snaking_main", label_ar: "تسليك صرف رئيسي", unit_ar: "فتحة" },
      { key: "pipe_leak_repair", label_ar: "إصلاح تسريب مواسير", unit_ar: "قطعة" },
      { key: "water_pipe_fix", label_ar: "تغيير جزء من ماسورة مياه", unit_ar: "متر" },
      { key: "drain_pipe_fix", label_ar: "تغيير جزء من ماسورة صرف", unit_ar: "متر" },
      { key: "filter_install", label_ar: "تركيب فلتر مياه", unit_ar: "قطعة" },
      { key: "valve_install", label_ar: "تركيب محبس", unit_ar: "قطعة" },
      { key: "sevo_install", label_ar: "تركيب سيفون", unit_ar: "قطعة" },
      { key: "shower_install", label_ar: "تركيب دش أو سماعة دش", unit_ar: "قطعة" },
      { key: "tub_install", label_ar: "تركيب بانيو أو كابينة دش", unit_ar: "قطعة" },
      { key: "toilet_repair", label_ar: "إصلاح أو تغيير طرد الحمام", unit_ar: "قطعة" },
      { key: "bath_pipes_setup", label_ar: "تأسيس سباكة حمام", unit_ar: "شغلانة" },
      { key: "kitchen_pipes_setup", label_ar: "تأسيس سباكة مطبخ", unit_ar: "شغلانة" },
    ],
  },
  "كهربائي": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل", unit_ar: "ساعة" },
      { key: "power_point", label_ar: "نقطة كهرباء جديدة (فيشة أو إضاءة)", unit_ar: "نقطة" },
      { key: "chandelier_install", label_ar: "تركيب ثريا أو وشيفة", unit_ar: "قطعة" },
      { key: "switch_install", label_ar: "تركيب مفتاح كهرباء", unit_ar: "قطعة" },
      { key: "socket_install", label_ar: "تركيب بريزة/فيشة", unit_ar: "قطعة" },
      { key: "ceiling_lamp_install", label_ar: "تركيب نجفة", unit_ar: "قطعة" },
      { key: "sconce_install", label_ar: "تركيب أبليك", unit_ar: "قطعة" },
      { key: "floodlight_install", label_ar: "تركيب كشاف", unit_ar: "قطعة" },
      { key: "spotlight_install", label_ar: "تركيب سبوت لايت", unit_ar: "قطعة" },
      { key: "led_strip_install", label_ar: "تركيب شريط LED", unit_ar: "متر" },
      { key: "ceiling_fan", label_ar: "تركيب مروحة سقف", unit_ar: "قطعة" },
      { key: "exhaust_fan", label_ar: "تركيب شفاط", unit_ar: "قطعة" },
      { key: "doorbell_install", label_ar: "تركيب جرس باب", unit_ar: "قطعة" },
      { key: "intercom_install", label_ar: "تركيب إنتركم", unit_ar: "قطعة" },
      { key: "panel_install", label_ar: "تركيب لوحة كهرباء", unit_ar: "قطعة" },
      { key: "breaker_install", label_ar: "تركيب قاطع كهرباء", unit_ar: "قطعة" },
      { key: "fault_repair", label_ar: "إصلاح عطل كهربائي", unit_ar: "شغلانة" },
      { key: "cable_change", label_ar: "تغيير سلك/كابل", unit_ar: "متر" },
      { key: "apartment_wiring", label_ar: "تأسيس كهرباء شقة", unit_ar: "شقة" },
      { key: "meter_install", label_ar: "تركيب عداد/توصيلات كهربائية", unit_ar: "قطعة" },
      { key: "cctv_install", label_ar: "تركيب كاميرات مراقبة", unit_ar: "كاميرا" },
      { key: "motion_sensor", label_ar: "تركيب حساس حركة", unit_ar: "قطعة" },
      { key: "timer_install", label_ar: "تركيب مؤقت/تايمر كهربائي", unit_ar: "قطعة" },
    ],
  },
"نجار": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل (تفصيلات)", unit_ar: "ساعة" },
      { key: "door_install", label_ar: "تركيب باب", unit_ar: "باب" },
      { key: "kitchen_unit", label_ar: "عمل أو تصليح دولاب/مطبخ", unit_ar: "وحدة" },
      { key: "furniture_repair", label_ar: "تصليح قطعة أثاث", unit_ar: "قطعة" },
      { key: "wood_window_install", label_ar: "تركيب شباك خشب", unit_ar: "شباك" },
      { key: "wood_door_repair", label_ar: "تصليح باب خشب", unit_ar: "باب" },
      { key: "window_repair_carp", label_ar: "تصليح شباك", unit_ar: "شباك" },
      { key: "lock_change", label_ar: "تغيير كالون باب", unit_ar: "قطعة" },
      { key: "hinge_change_najar", label_ar: "تغيير مفصلات", unit_ar: "مفصل" },
      { key: "door_handle_install", label_ar: "تركيب مقبض باب", unit_ar: "قطعة" },
      { key: "leaf_install", label_ar: "تركيب ضلفة باب", unit_ar: "ضلفة" },
      { key: "sliding_door", label_ar: "تركيب باب جرار", unit_ar: "باب" },
      { key: "shelves_make", label_ar: "تفصيل رفوف", unit_ar: "رف" },
      { key: "library_make", label_ar: "تفصيل مكتبة", unit_ar: "قطعة" },
      { key: "table_make", label_ar: "تفصيل ترابيزة", unit_ar: "قطعة" },
      { key: "desk_make", label_ar: "تفصيل مكتب", unit_ar: "قطعة" },
      { key: "bed_make", label_ar: "تفصيل سرير", unit_ar: "قطعة" },
      { key: "shoe_cabinet", label_ar: "تفصيل جزامة", unit_ar: "قطعة" },
      { key: "tv_unit_make", label_ar: "تفصيل وحدة تلفزيون", unit_ar: "قطعة" },
      { key: "wood_kitchen_make", label_ar: "تفصيل مطبخ خشب", unit_ar: "متر طولي" },
      { key: "kitchen_install_najar", label_ar: "تركيب مطبخ", unit_ar: "متر طولي" },
      { key: "wardrobe_install", label_ar: "تركيب دولاب جاهز", unit_ar: "قطعة" },
      { key: "drawer_repair", label_ar: "إصلاح أدراج", unit_ar: "درج" },
      { key: "wood_replace", label_ar: "تغيير خشب تالف", unit_ar: "قطعة" },
      { key: "furniture_polish", label_ar: "تلميع/دهان أثاث خشبي", unit_ar: "قطعة" },
    ],
  },
  "نقاش": {
    items: [
      { key: "wall_painting", label_ar: "دهان حوائط (مع المعجون والسنفرة)", unit_ar: "متر²" },
      { key: "ceiling_painting", label_ar: "دهان أسقف", unit_ar: "متر²" },
      { key: "wood_painting", label_ar: "دهان أبواب وشبابيك خشب", unit_ar: "قطعة" },
      { key: "metal_doors_paint", label_ar: "دهان أبواب وشبابيك حديد", unit_ar: "قطعة" },
      { key: "room_painting", label_ar: "دهان غرف كاملة", unit_ar: "غرفة" },
      { key: "apartment_painting", label_ar: "دهان شقة كاملة", unit_ar: "شقة" },
      { key: "wall_paste", label_ar: "معجون حوائط", unit_ar: "متر²" },
      { key: "wall_crack_fix", label_ar: "معالجة شروخ الحوائط", unit_ar: "متر طولي" },
      { key: "damp_treat_paint", label_ar: "معالجة الرطوبة", unit_ar: "متر²" },
      { key: "old_paint_remove", label_ar: "إزالة دهان قديم", unit_ar: "متر²" },
      { key: "sanding_prep", label_ar: "صنفرة وتجهيز الحوائط", unit_ar: "متر²" },
      { key: "plastic_paint", label_ar: "دهان بلاستيك", unit_ar: "متر²" },
      { key: "lacquer_paint", label_ar: "دهان لاكيه", unit_ar: "متر²" },
      { key: "duco_paint", label_ar: "دهان دوكو", unit_ar: "متر²" },
      { key: "iron_doors_paint", label_ar: "دهان أبواب حديد", unit_ar: "باب" },
      { key: "iron_windows_paint", label_ar: "دهان شبابيك حديد", unit_ar: "شباك" },
      { key: "wallpaper_remove", label_ar: "ورق حائط", unit_ar: "متر²" },
      { key: "wallpaper_install", label_ar: "تركيب ورق حائط", unit_ar: "متر²" },
      { key: "wall_decor_paint", label_ar: "ديكورات حوائط", unit_ar: "متر²" },
      { key: "stucco", label_ar: "استوكو", unit_ar: "متر²" },
      { key: "velvet_texture", label_ar: "فلفت/ملمس ديكوري", unit_ar: "متر²" },
      { key: "spray_paint", label_ar: "رش دهان", unit_ar: "متر²" },
    ],
  },
  "تكييف": {
    items: [
      { key: "ac_install", label_ar: "تركيب تكييف سبليت أو شباك", unit_ar: "وحدة" },
      { key: "ac_service", label_ar: "تنظيف وصيانة تكييف", unit_ar: "وحدة" },
      { key: "copper_pipe", label_ar: "مواسير نحاس إضافية", unit_ar: "متر" },
      { key: "ac_remove", label_ar: "فك تكييف", unit_ar: "وحدة" },
      { key: "ac_move", label_ar: "نقل تكييف", unit_ar: "وحدة" },
      { key: "freon_charge", label_ar: "شحن فريون", unit_ar: "وحدة" },
      { key: "freon_leak_check", label_ar: "كشف تسريب فريون", unit_ar: "وحدة" },
      { key: "freon_leak_repair", label_ar: "إصلاح تسريب فريون", unit_ar: "وحدة" },
      { key: "condenser_change", label_ar: "تغيير مكثف", unit_ar: "قطعة" },
      { key: "fan_motor_change", label_ar: "تغيير موتور مروحة", unit_ar: "قطعة" },
      { key: "ac_circuit_repair", label_ar: "إصلاح دائرة كهرباء التكييف", unit_ar: "شغلانة" },
      { key: "board_change", label_ar: "تغيير لوحة إلكترونية", unit_ar: "قطعة" },
      { key: "sensor_change", label_ar: "تغيير حساس", unit_ar: "قطعة" },
      { key: "capacitor_change", label_ar: "تغيير كابستور", unit_ar: "قطعة" },
      { key: "indoor_clean", label_ar: "تنظيف الوحدة الداخلية", unit_ar: "وحدة" },
      { key: "outdoor_clean", label_ar: "تنظيف الوحدة الخارجية", unit_ar: "وحدة" },
      { key: "ac_drain_install", label_ar: "تركيب صرف تكييف", unit_ar: "متر" },
      { key: "ac_setup", label_ar: "تأسيس تكييف", unit_ar: "شغلانة" },
      { key: "pipe_insulation", label_ar: "عزل مواسير التكييف", unit_ar: "متر" },
      { key: "ac_water_leak_fix", label_ar: "إصلاح تسريب مياه من التكييف", unit_ar: "وحدة" },
    ],
  },
  "بناء وواجهات حجرية": {
    items: [
      { key: "brick_m3", label_ar: "أعمال بناء طوب", unit_ar: "متر³" },
      { key: "stone_facade", label_ar: "واجهة حجر طبيعي", unit_ar: "متر²" },
      { key: "brick_wall_sqm", label_ar: "حائط طوب (تقسيمة أو ردم)", unit_ar: "متر²" },
      { key: "block_build", label_ar: "مباني بلوك", unit_ar: "متر²" },
      { key: "red_brick_build", label_ar: "مباني طوب أحمر", unit_ar: "متر²" },
      { key: "wall_demolish", label_ar: "هدم حائط", unit_ar: "متر²" },
      { key: "wall_breaking", label_ar: "تكسير حائط", unit_ar: "متر²" },
      { key: "wall_build", label_ar: "بناء حائط", unit_ar: "متر²" },
      { key: "wall_plaster_build", label_ar: "محارة حوائط", unit_ar: "متر²" },
      { key: "ceiling_plaster_build", label_ar: "محارة أسقف", unit_ar: "متر²" },
      { key: "wall_restore", label_ar: "ترميم حوائط", unit_ar: "متر²" },
      { key: "crack_restore", label_ar: "ترميم شروخ", unit_ar: "متر طولي" },
      { key: "hashimy_stone", label_ar: "تركيب حجر هاشمي", unit_ar: "متر²" },
      { key: "pharaonic_stone", label_ar: "تركيب حجر فرعوني", unit_ar: "متر²" },
      { key: "marble_install_build", label_ar: "تركيب رخام", unit_ar: "متر²" },
      { key: "granite_install_build", label_ar: "تركيب جرانيت", unit_ar: "متر²" },
      { key: "tiles_install_build", label_ar: "تركيب بلاط/سيراميك", unit_ar: "متر²" },
      { key: "skirting_install_build", label_ar: "تركيب وزرات", unit_ar: "متر طولي" },
      { key: "threshold_install", label_ar: "عمل عتبة باب أو شباك", unit_ar: "قطعة" },
      { key: "level_plaster", label_ar: "تلييس وتسوية الحوائط", unit_ar: "متر²" },
      { key: "roof_insulation", label_ar: "عزل أسطح", unit_ar: "متر²" },
      { key: "wall_insulation", label_ar: "عزل حوائط", unit_ar: "متر²" },
      { key: "facade_restore_build", label_ar: "ترميم واجهات", unit_ar: "متر²" },
      { key: "facade_clean", label_ar: "تنظيف واجهات حجر", unit_ar: "متر²" },
      { key: "old_stone_remove", label_ar: "تكسير وإزالة حجر قديم", unit_ar: "متر²" },
    ],
  },
  "سيراميك": {
    items: [
      { key: "floor_tiles", label_ar: "تركيب سيراميك أرضيات", unit_ar: "متر²" },
      { key: "wall_tiles", label_ar: "تركيب سيراميك حوائط", unit_ar: "متر²" },
      { key: "stair_cladding", label_ar: "تكسية درج سيراميك", unit_ar: "درجة" },
      { key: "work_hour", label_ar: "ساعة عمل (تركيب وتصليحات)", unit_ar: "ساعة" },
      { key: "porcelain_floor", label_ar: "تركيب بورسلين أرضيات", unit_ar: "متر²" },
      { key: "porcelain_wall", label_ar: "تركيب بورسلين حوائط", unit_ar: "متر²" },
      { key: "mosaic_install", label_ar: "تركيب موزاييك", unit_ar: "متر²" },
      { key: "tiles_skirting", label_ar: "تركيب وزرات سيراميك", unit_ar: "متر طولي" },
      { key: "bath_tiles", label_ar: "تركيب سيراميك حمام", unit_ar: "متر²" },
      { key: "kitchen_tiles", label_ar: "تركيب سيراميك مطبخ", unit_ar: "متر²" },
      { key: "old_tiles_remove", label_ar: "إزالة سيراميك قديم", unit_ar: "متر²" },
      { key: "floor_prepare", label_ar: "تكسير وتجهيز الأرضية", unit_ar: "متر²" },
      { key: "floor_level", label_ar: "تسوية الأرضية قبل التركيب", unit_ar: "متر²" },
      { key: "tiles_repair", label_ar: "إصلاح واستبدال سيراميك تالف", unit_ar: "متر²" },
      { key: "outdoor_tiles", label_ar: "تركيب بلاط خارجي", unit_ar: "متر²" },
      { key: "roof_tiles", label_ar: "تركيب بلاط سطح/روف", unit_ar: "متر²" },
      { key: "decor_stone_tiles", label_ar: "تركيب حجر ديكوري", unit_ar: "متر²" },
      { key: "floor_slope", label_ar: "عمل ميول للأرضيات", unit_ar: "متر²" },
      { key: "tiles_joins", label_ar: "تركيب فواصل وتمديدات السيراميك", unit_ar: "متر طولي" },
    ],
  },
  "باركيه": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل", unit_ar: "ساعة" },
      { key: "laminate_install", label_ar: "تركيب باركيه أو لامينيت", unit_ar: "متر²" },
      { key: "natural_install", label_ar: "تركيب باركيه خشب طبيعي", unit_ar: "متر²" },
      { key: "engineered_install", label_ar: "تركيب باركيه هندسي", unit_ar: "متر²" },
      { key: "spc_install", label_ar: "تركيب أرضيات SPC", unit_ar: "متر²" },
      { key: "vinyl_install", label_ar: "تركيب أرضيات Vinyl", unit_ar: "متر²" },
      { key: "removal_old", label_ar: "إزالة باركيه قديم", unit_ar: "متر²" },
      { key: "repair_damaged", label_ar: "إصلاح باركيه تالف", unit_ar: "متر²" },
      { key: "replace_plank", label_ar: "تغيير ألواح باركيه", unit_ar: "لوح" },
      { key: "sanding", label_ar: "صنفرة باركيه", unit_ar: "متر²" },
      { key: "polish", label_ar: "تلميع باركيه", unit_ar: "متر²" },
      { key: "wax_polish", label_ar: "دهان/تلميع باركيه", unit_ar: "متر²" },
      { key: "swell_fix", label_ar: "معالجة انتفاخ الباركيه", unit_ar: "متر²" },
      { key: "gap_fix", label_ar: "معالجة فواصل الباركيه", unit_ar: "متر طولي" },
      { key: "thresholds", label_ar: "تركيب عتبات وفواصل أرضيات", unit_ar: "قطعة" },
      { key: "wood_skirting", label_ar: "تركيب وزرات خشب", unit_ar: "متر طولي" },
      { key: "stairs_install", label_ar: "تركيب باركيه على السلالم", unit_ar: "درجة" },
    ],
  },
  "حداد": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل", unit_ar: "ساعة" },
      { key: "railing_meter", label_ar: "درابزين أو سياج حديد", unit_ar: "متر طولي" },
      { key: "steel_door", label_ar: "باب حديد (تصنيع وتركيب)", unit_ar: "باب" },
      { key: "steel_window", label_ar: "شباك حديد (تصنيع وتركيب)", unit_ar: "شباك" },
      { key: "iron_gate", label_ar: "بوابة حديد", unit_ar: "بوابة" },
      { key: "iron_fence", label_ar: "سور حديد", unit_ar: "متر طولي" },
      { key: "iron_stairs", label_ar: "سلم حديد", unit_ar: "درجة" },
      { key: "canopy", label_ar: "مظلة/برجولة حديد", unit_ar: "متر²" },
      { key: "ac_bracket", label_ar: "حامل تكييف", unit_ar: "قطعة" },
      { key: "heater_bracket", label_ar: "حامل سخان", unit_ar: "قطعة" },
      { key: "tank_bracket", label_ar: "حامل خزانات", unit_ar: "قطعة" },
      { key: "barriers_gates", label_ar: "حواجز وبوابات", unit_ar: "قطعة" },
      { key: "protective_mesh", label_ar: "شبك حماية", unit_ar: "متر²" },
      { key: "metal_net_install", label_ar: "تركيب شبك معدني", unit_ar: "متر²" },
      { key: "welding_repair", label_ar: "لحام وتصليح حديد", unit_ar: "قطعة" },
      { key: "door_repair", label_ar: "إصلاح باب حديد", unit_ar: "باب" },
      { key: "window_repair", label_ar: "إصلاح شباك حديد", unit_ar: "شباك" },
      { key: "hinge_change", label_ar: "تغيير مفصلات باب/بوابة", unit_ar: "مفصل" },
      { key: "padlock_caloon", label_ar: "تركيب كالون باب حديد", unit_ar: "قطعة" },
      { key: "iron_paint", label_ar: "دهان حديد", unit_ar: "متر²" },
      { key: "rust_treatment", label_ar: "إزالة صدأ ومعالجة الحديد", unit_ar: "متر²" },
      { key: "iron_shelves", label_ar: "تصنيع وتركيب رفوف حديد", unit_ar: "قطعة" },
      { key: "metal_furniture", label_ar: "تصنيع وتركيب أثاث معدني", unit_ar: "قطعة" },
    ],
  },
  "محارة": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل", unit_ar: "ساعة" },
      { key: "interior_plaster", label_ar: "محارة داخلية (تسوية الحوائط من الداخل)", unit_ar: "متر²" },
      { key: "exterior_plaster", label_ar: "محارة خارجية (محارة الواجهة من الخارج)", unit_ar: "متر²" },
      { key: "ceiling_plaster", label_ar: "محارة أسقف", unit_ar: "متر²" },
      { key: "facade_plaster", label_ar: "محارة واجهات", unit_ar: "متر²" },
      { key: "scratch_coat", label_ar: "طرطشة حوائط", unit_ar: "متر²" },
      { key: "guide_battoj", label_ar: "بؤج وأوتار", unit_ar: "متر طولي" },
      { key: "crack_treat", label_ar: "معالجة شروخ المحارة", unit_ar: "متر طولي" },
      { key: "old_plaster_restore", label_ar: "ترميم محارة قديمة", unit_ar: "متر²" },
      { key: "old_plaster_remove", label_ar: "إزالة محارة تالفة", unit_ar: "متر²" },
      { key: "damp_treat", label_ar: "معالجة رطوبة الحوائط", unit_ar: "متر²" },
      { key: "wall_leveling", label_ar: "تسوية وتجهيز الحوائط", unit_ar: "متر²" },
      { key: "cement_plaster", label_ar: "محارة إسمنتية", unit_ar: "متر²" },
      { key: "lime_plaster", label_ar: "محارة جيرية", unit_ar: "متر²" },
      { key: "decorative_plaster", label_ar: "محارة ديكورية", unit_ar: "متر²" },
      { key: "doors_windows_plaster", label_ar: "محارة حول الشبابيك والأبواب", unit_ar: "متر²" },
      { key: "kitchen_bath_plaster", label_ar: "محارة الحمامات والمطابخ", unit_ar: "متر²" },
      { key: "roof_slope", label_ar: "عمل ميول للأسطح", unit_ar: "متر²" },
      { key: "facade_restore", label_ar: "ترميم واجهات المباني", unit_ar: "متر²" },
    ],
  },
  "رخام وجرانيت": {
    items: [
      { key: "work_hour", label_ar: "ساعة عمل", unit_ar: "ساعة" },
      { key: "marble_floor", label_ar: "تركيب رخام أو جرانيت أرضيات", unit_ar: "متر²" },
      { key: "stairs_defaya", label_ar: "دفايات درج رخام/جرانيت", unit_ar: "متر طولي" },
      { key: "countertop", label_ar: "سطح مطبخ أو حمام رخام", unit_ar: "متر طولي" },
      { key: "wall_marble", label_ar: "تركيب رخام حوائط", unit_ar: "متر²" },
      { key: "wall_granite", label_ar: "تركيب جرانيت حوائط", unit_ar: "متر²" },
      { key: "stairs_marble", label_ar: "تركيب رخام السلالم", unit_ar: "درجة" },
      { key: "stairs_granite", label_ar: "تركيب جرانيت السلالم", unit_ar: "درجة" },
      { key: "skirting_marble", label_ar: "تركيب وزرات رخام", unit_ar: "متر طولي" },
      { key: "thresholds_marble", label_ar: "تركيب عتبات أبواب وشبابيك", unit_ar: "قطعة" },
      { key: "kitchen_marble", label_ar: "تركيب رخام مطابخ", unit_ar: "متر طولي" },
      { key: "bath_marble", label_ar: "تركيب رخام حمامات", unit_ar: "متر²" },
      { key: "basin_marble", label_ar: "تركيب أحواض رخام", unit_ar: "قطعة" },
      { key: "custom_basin", label_ar: "تفصيل وتركيب حوض رخام", unit_ar: "قطعة" },
      { key: "cut_marble", label_ar: "قص وتفصيل الرخام", unit_ar: "متر²" },
      { key: "cut_granite", label_ar: "قص وتفصيل الجرانيت", unit_ar: "متر²" },
      { key: "polish_marble", label_ar: "جلي رخام", unit_ar: "متر²" },
      { key: "shine_marble", label_ar: "تلميع رخام", unit_ar: "متر²" },
      { key: "polish_granite", label_ar: "جلي وتلميع جرانيت", unit_ar: "متر²" },
      { key: "marble_repair", label_ar: "إصلاح وترميم رخام", unit_ar: "قطعة" },
      { key: "crack_repair", label_ar: "إصلاح كسر أو شرخ", unit_ar: "قطعة" },
      { key: "replace_piece", label_ar: "تغيير قطعة رخام تالفة", unit_ar: "قطعة" },
      { key: "old_marble_remove", label_ar: "إزالة رخام قديم", unit_ar: "متر²" },
      { key: "tabletop_marble", label_ar: "تركيب رخامة ترابيزة", unit_ar: "قطعة" },
      { key: "facade_marble", label_ar: "تركيب رخام واجهات", unit_ar: "متر²" },
      { key: "stair_marble", label_ar: "تركيب رخام درج", unit_ar: "درجة" },
    ],
  },
  "جبسيوم بورد": {
    items: [
      { key: "ceiling_install", label_ar: "تركيب سقف جبس بورد", unit_ar: "متر²" },
      { key: "false_ceiling", label_ar: "أسقف مستورة جبس بورد", unit_ar: "متر²" },
      { key: "normal_ceiling", label_ar: "سقف جبس بورد عادي", unit_ar: "متر²" },
      { key: "suspended_ceiling", label_ar: "سقف معلق جبس بورد", unit_ar: "متر²" },
      { key: "flat_ceiling", label_ar: "سقف مستوي جبس بورد", unit_ar: "متر²" },
      { key: "multi_level_ceiling", label_ar: "سقف مستويات جبس بورد", unit_ar: "متر²" },
      { key: "decorative_ceiling", label_ar: "سقف ديكوري جبس بورد", unit_ar: "متر²" },
      { key: "gypsum_cornice", label_ar: "كورنيش جبس بورد", unit_ar: "متر طولي" },
      { key: "light_box", label_ar: "لايت بوكس وتجليبات إضاءة", unit_ar: "متر طولي" },
      { key: "house_noor", label_ar: "بيت نور جبس بورد", unit_ar: "قطعة" },
      { key: "curtain_box", label_ar: "بيت ستارة جبس بورد", unit_ar: "قطعة" },
      { key: "wall_casing", label_ar: "تجليدة حائط جبس بورد", unit_ar: "متر²" },
      { key: "bookshelf_gb", label_ar: "مكتبة جبس بورد", unit_ar: "قطعة" },
      { key: "tv_wall_gb", label_ar: "شاشة TV جبس بورد", unit_ar: "قطعة" },
      { key: "tv_backdrop", label_ar: "خلفية تلفزيون جبس بورد", unit_ar: "متر²" },
      { key: "partition_gb", label_ar: "فاصل جبس بورد", unit_ar: "متر²" },
      { key: "wall_partition", label_ar: "قواطع جبس بورد", unit_ar: "متر²" },
      { key: "room_dividers", label_ar: "تقسيم غرف بالجبس بورد", unit_ar: "متر²" },
      { key: "column_casing", label_ar: "تجليد أعمدة بالجبس بورد", unit_ar: "متر²" },
      { key: "gb_shelves", label_ar: "رفوف جبس بورد", unit_ar: "قطعة" },
      { key: "decor_units", label_ar: "وحدات ديكورية جبس بورد", unit_ar: "وحدة" },
      { key: "gb_cornices", label_ar: "كرانيش جبس بورد", unit_ar: "متر طولي" },
      { key: "lighting_cornice", label_ar: "كرانيش إضاءة", unit_ar: "متر طولي" },
      { key: "light_box_only", label_ar: "لايت بوكس", unit_ar: "قطعة" },
      { key: "hidden_lighting", label_ar: "بيت إضاءة مخفي", unit_ar: "قطعة" },
      { key: "spotlight_holes", label_ar: "فتحات سبوت لايت", unit_ar: "فتحة" },
      { key: "ac_holes", label_ar: "فتحات تكييف", unit_ar: "فتحة" },
      { key: "speaker_holes", label_ar: "فتحات سماعات", unit_ar: "فتحة" },
      { key: "spotlight_mount", label_ar: "تركيب كشافات داخل الجبس", unit_ar: "قطعة" },
      { key: "join_treat", label_ar: "معالجة فواصل الجبس بورد", unit_ar: "متر طولي" },
      { key: "joint_compound", label_ar: "معجون جبس بورد", unit_ar: "متر²" },
      { key: "sanding_gb", label_ar: "صنفرة جبس بورد", unit_ar: "متر²" },
      { key: "painting_gb", label_ar: "دهان جبس بورد", unit_ar: "متر²" },
      { key: "repair_gb", label_ar: "إصلاح جبس بورد", unit_ar: "متر²" },
      { key: "replace_part", label_ar: "تغيير جزء تالف من الجبس بورد", unit_ar: "متر²" },
      { key: "dismantle_gb", label_ar: "فك جبس بورد", unit_ar: "متر²" },
      { key: "remove_move_gb", label_ar: "فك ونقل جبس بورد", unit_ar: "متر²" },
      { key: "sound_insulation", label_ar: "عزل صوتي داخل الجبس بورد", unit_ar: "متر²" },
      { key: "partition_insulation", label_ar: "تركيب عازل داخل القواطع", unit_ar: "متر²" },
    ],
  },
  "جبس بلدي ومصيص": {
    items: [
      { key: "ceiling_gypsum", label_ar: "جبس بلدي أسقف", unit_ar: "متر²" },
      { key: "wall_gypsum", label_ar: "جبس بلدي حوائط", unit_ar: "متر²" },
      { key: "local_gypsum", label_ar: "جبس بلدي (زخارف)", unit_ar: "متر²" },
      { key: "gypsum_decor", label_ar: "زخارف جبس بلدي", unit_ar: "قطعة" },
      { key: "gypsum_cornices_b", label_ar: "كرانيش جبس بلدي", unit_ar: "متر طولي" },
      { key: "plaster_cornice", label_ar: "كورنيش جبس", unit_ar: "متر طولي" },
      { key: "beam_rosette", label_ar: "روزيت جبس", unit_ar: "قطعة" },
      { key: "gypsum_flower", label_ar: "ورد جبس", unit_ar: "قطعة" },
      { key: "ceiling_decor", label_ar: "زخارف سقف", unit_ar: "قطعة" },
      { key: "wall_decor", label_ar: "زخارف حائط", unit_ar: "قطعة" },
      { key: "gypsum_panels", label_ar: "بانوهات جبس", unit_ar: "قطعة" },
      { key: "gypsum_frames", label_ar: "إطارات جبس", unit_ar: "قطعة" },
      { key: "decor_columns", label_ar: "أعمدة جبس ديكورية", unit_ar: "قطعة" },
      { key: "gypsum_arches", label_ar: "أقواس جبس", unit_ar: "قطعة" },
      { key: "gypsum_domes", label_ar: "قباب جبس", unit_ar: "قطعة" },
      { key: "house_noor_b", label_ar: "بيت نور جبس بلدي", unit_ar: "قطعة" },
      { key: "curtain_box_b", label_ar: "بيت ستارة جبس بلدي", unit_ar: "قطعة" },
      { key: "column_wrap_g", label_ar: "تجليد أعمدة بالجبس", unit_ar: "قطعة" },
      { key: "decor_repair", label_ar: "إصلاح زخارف جبس", unit_ar: "قطعة" },
      { key: "decor_remove", label_ar: "فك زخارف جبس", unit_ar: "قطعة" },
      { key: "masis_walls", label_ar: "مصيص حوائط", unit_ar: "متر²" },
      { key: "masis_ceiling", label_ar: "مصيص أسقف", unit_ar: "متر²" },
      { key: "masis_room", label_ar: "مصيص غرفة", unit_ar: "غرفة" },
      { key: "masis_apartment", label_ar: "مصيص شقة كاملة", unit_ar: "شقة" },
      { key: "scratch_walls", label_ar: "طرطشة حوائط", unit_ar: "متر²" },
      { key: "scratch_ceiling", label_ar: "طرطشة أسقف", unit_ar: "متر²" },
      { key: "level_walls", label_ar: "تلييس حوائط", unit_ar: "متر²" },
      { key: "level_ceiling", label_ar: "تلييس أسقف", unit_ar: "متر²" },
      { key: "align_walls", label_ar: "تسوية حوائط", unit_ar: "متر²" },
      { key: "align_ceiling", label_ar: "تسوية أسقف", unit_ar: "متر²" },
      { key: "crack_fix", label_ar: "معالجة شروخ", unit_ar: "متر طولي" },
      { key: "honeycomb_fix", label_ar: "معالجة تعشيش", unit_ar: "متر²" },
      { key: "damp_pretreat", label_ar: "معالجة رطوبة قبل المصيص", unit_ar: "متر²" },
      { key: "old_masis_repair", label_ar: "ترميم مصيص قديم", unit_ar: "متر²" },
      { key: "old_masis_remove", label_ar: "إزالة مصيص قديم", unit_ar: "متر²" },
      { key: "door_casing_finish", label_ar: "تشطيب فتحات الأبواب", unit_ar: "فتحة" },
      { key: "window_casing_finish", label_ar: "تشطيب فتحات الشبابيك", unit_ar: "فتحة" },
      { key: "corners_finish", label_ar: "تشطيب زوايا الحوائط", unit_ar: "متر طولي" },
      { key: "prep_painting", label_ar: "تجهيز الحوائط للدهان", unit_ar: "متر²" },
    ],
  },
  "ستائر وتنجيد": {
    items: [
      { key: "curtain_meter", label_ar: "ستائر (قماش وتركيب)", unit_ar: "متر طولي" },
      { key: "cornice_install", label_ar: "تركيب كورنيش ستائر", unit_ar: "متر طولي" },
      { key: "upholstery", label_ar: "تنجيد كرسي أو قطعة أثاث", unit_ar: "قطعة" },
      { key: "curtain_tailoring", label_ar: "تفصيل ستائر", unit_ar: "متر طولي" },
      { key: "curtain_install_only", label_ar: "تركيب ستائر", unit_ar: "نافذة" },
      { key: "curtain_remove", label_ar: "فك ستائر", unit_ar: "نافذة" },
      { key: "curtain_rm_install", label_ar: "فك وتركيب ستائر", unit_ar: "نافذة" },
      { key: "blackout_curtain", label_ar: "ستائر بلاك أوت", unit_ar: "نافذة" },
      { key: "roller_curtain", label_ar: "ستائر رول", unit_ar: "نافذة" },
      { key: "zebra_curtain", label_ar: "ستائر زيبرا", unit_ar: "نافذة" },
      { key: "roman_curtain", label_ar: "ستائر روماني", unit_ar: "نافذة" },
      { key: "office_curtain", label_ar: "ستائر مكتب", unit_ar: "نافذة" },
      { key: "bedroom_curtain", label_ar: "ستائر غرفة نوم", unit_ar: "نافذة" },
      { key: "kids_curtain", label_ar: "ستائر غرفة أطفال", unit_ar: "نافذة" },
      { key: "salon_curtain", label_ar: "ستائر صالون", unit_ar: "نافذة" },
      { key: "balcony_curtain", label_ar: "ستائر بلكونة", unit_ar: "نافذة" },
      { key: "window_curtain", label_ar: "ستائر شباك", unit_ar: "نافذة" },
      { key: "door_curtain", label_ar: "ستائر باب", unit_ar: "باب" },
      { key: "hotel_curtain", label_ar: "ستائر فندقية", unit_ar: "نافذة" },
      { key: "theater_curtain", label_ar: "ستائر مسرح", unit_ar: "متر²" },
      { key: "shop_curtain", label_ar: "ستائر محلات", unit_ar: "متر²" },
      { key: "curtain_pole_install", label_ar: "تركيب ماسورة ستارة", unit_ar: "متر طولي" },
      { key: "curtain_track_install", label_ar: "تركيب مسار ستارة", unit_ar: "متر طولي" },
      { key: "hidden_track_install", label_ar: "تركيب مسار ستارة مخفي", unit_ar: "متر طولي" },
      { key: "motorized_track", label_ar: "تركيب مسار كهربائي", unit_ar: "متر طولي" },
      { key: "curtain_holder", label_ar: "تركيب حوامل ستائر", unit_ar: "قطعة" },
      { key: "track_change", label_ar: "تغيير مسار ستارة", unit_ar: "متر طولي" },
      { key: "track_repair", label_ar: "إصلاح مسار ستارة", unit_ar: "متر طولي" },
      { key: "accs_change", label_ar: "تغيير إكسسوارات الستارة", unit_ar: "قطعة" },
      { key: "chair_upholster", label_ar: "تنجيد كرسي", unit_ar: "كرسي" },
      { key: "sofa_upholster", label_ar: "تنجيد كنبة", unit_ar: "كنبة" },
      { key: "armchair_upholster", label_ar: "تنجيد فوتيه", unit_ar: "قطعة" },
      { key: "dining_chairs", label_ar: "تنجيد كراسي سفرة", unit_ar: "كرسي" },
      { key: "settee_upholster", label_ar: "تنجيد أنتريه", unit_ar: "قطعة" },
      { key: "bed_upholster", label_ar: "تنجيد سرير", unit_ar: "قطعة" },
      { key: "headboard_upholster", label_ar: "تنجيد ظهر سرير", unit_ar: "قطعة" },
      { key: "chair_fabric", label_ar: "تغيير قماش كرسي", unit_ar: "كرسي" },
      { key: "sofa_fabric", label_ar: "تغيير قماش كنبة", unit_ar: "كنبة" },
      { key: "foam_change", label_ar: "تغيير إسفنج", unit_ar: "قطعة" },
      { key: "wood_repair_uph", label_ar: "إصلاح خشب الأثاث", unit_ar: "قطعة" },
      { key: "legs_change", label_ar: "تغيير أرجل الأثاث", unit_ar: "قطعة" },
      { key: "reupholster", label_ar: "إعادة تنجيد قطعة أثاث", unit_ar: "قطعة" },
      { key: "furniture_clean", label_ar: "تنظيف وتلميع الأثاث", unit_ar: "قطعة" },
    ],
  },
  "زجاج وسيكوريت": {
    items: [
      { key: "aluminum_window", label_ar: "شبابيك أو واجهة سيكوريت", unit_ar: "متر²" },
      { key: "mirror_sqm", label_ar: "مرايا وزجاج", unit_ar: "متر²" },
      { key: "shower_enclosure", label_ar: "كابينة شاور زجاج", unit_ar: "وحدة" },
      { key: "plain_glass", label_ar: "تركيب زجاج عادي", unit_ar: "متر²" },
      { key: "clear_glass", label_ar: "تركيب زجاج شفاف", unit_ar: "متر²" },
      { key: "tinted_glass", label_ar: "تركيب زجاج ملون", unit_ar: "متر²" },
      { key: "reflective_glass", label_ar: "تركيب زجاج عاكس", unit_ar: "متر²" },
      { key: "security_glass", label_ar: "تركيب زجاج سيكوريت", unit_ar: "متر²" },
      { key: "window_glass_change", label_ar: "تغيير زجاج شباك", unit_ar: "شباك" },
      { key: "door_glass_change", label_ar: "تغيير زجاج باب", unit_ar: "باب" },
      { key: "facade_glass_change", label_ar: "تغيير زجاج واجهة", unit_ar: "متر²" },
      { key: "glass_cutting", label_ar: "قص زجاج", unit_ar: "متر²" },
      { key: "office_glass", label_ar: "تركيب زجاج للمكاتب", unit_ar: "متر²" },
      { key: "shop_glass", label_ar: "تركيب زجاج للمحلات", unit_ar: "متر²" },
      { key: "balcony_glass", label_ar: "تركيب زجاج للبلكونة", unit_ar: "متر²" },
      { key: "kitchen_glass", label_ar: "تركيب زجاج للمطابخ", unit_ar: "متر²" },
      { key: "restaurant_glass", label_ar: "تركيب زجاج للمطاعم", unit_ar: "متر²" },
      { key: "security_door", label_ar: "باب سيكوريت", unit_ar: "باب" },
      { key: "security_facade", label_ar: "واجهة سيكوريت", unit_ar: "متر²" },
      { key: "security_partitions", label_ar: "قواطع سيكوريت", unit_ar: "متر²" },
      { key: "security_window", label_ar: "شباك سيكوريت", unit_ar: "شباك" },
      { key: "secdoor_install", label_ar: "تركيب باب سيكوريت", unit_ar: "باب" },
      { key: "secfacade_install", label_ar: "تركيب واجهة سيكوريت", unit_ar: "متر²" },
      { key: "sechinge_install", label_ar: "تركيب مفصلات سيكوريت", unit_ar: "مفصل" },
      { key: "speclock_install", label_ar: "تركيب كالون سيكوريت", unit_ar: "قطعة" },
      { key: "sechandle_install", label_ar: "تركيب يد باب سيكوريت", unit_ar: "قطعة" },
      { key: "secaccs_install", label_ar: "تركيب إكسسوارات سيكوريت", unit_ar: "قطعة" },
      { key: "secaccs_change", label_ar: "تغيير إكسسوارات سيكوريت", unit_ar: "قطعة" },
      { key: "secdoor_repair", label_ar: "إصلاح باب سيكوريت", unit_ar: "باب" },
      { key: "secdoor_adjust", label_ar: "ضبط باب سيكوريت", unit_ar: "باب" },
      { key: "secglass_change", label_ar: "تغيير زجاج سيكوريت", unit_ar: "متر²" },
      { key: "mirror_install", label_ar: "تركيب مرايا", unit_ar: "متر²" },
      { key: "mirror_tailor", label_ar: "تفصيل مرايا", unit_ar: "متر²" },
      { key: "bath_mirror", label_ar: "مرايا حمام", unit_ar: "قطعة" },
      { key: "room_mirror", label_ar: "مرايا غرف", unit_ar: "قطعة" },
      { key: "decor_mirror", label_ar: "مرايا ديكور", unit_ar: "قطعة" },
      { key: "lit_mirror", label_ar: "مرايا بإضاءة", unit_ar: "قطعة" },
      { key: "large_mirror", label_ar: "مرايا كبيرة", unit_ar: "قطعة" },
      { key: "wall_mirror_install", label_ar: "تركيب مرايا حائط", unit_ar: "متر²" },
      { key: "mirror_remove", label_ar: "فك مرايا", unit_ar: "متر²" },
      { key: "mirror_replace", label_ar: "استبدال مرايا", unit_ar: "متر²" },
      { key: "shower_cab_install", label_ar: "تركيب كابينة شاور", unit_ar: "وحدة" },
      { key: "shower_cab_tailor", label_ar: "تفصيل كابينة شاور", unit_ar: "وحدة" },
      { key: "hinged_shower", label_ar: "كابينة شاور مفصلية", unit_ar: "وحدة" },
      { key: "sliding_shower", label_ar: "كابينة شاور سحب", unit_ar: "وحدة" },
      { key: "fixed_shower", label_ar: "كابينة شاور ثابتة", unit_ar: "وحدة" },
      { key: "shower_glass_change", label_ar: "تغيير زجاج كابينة", unit_ar: "متر²" },
      { key: "shower_hinge_change", label_ar: "تغيير مفصلات الكابينة", unit_ar: "مفصل" },
      { key: "shower_accs_change", label_ar: "تغيير إكسسوارات الكابينة", unit_ar: "قطعة" },
      { key: "shower_repair", label_ar: "إصلاح كابينة شاور", unit_ar: "وحدة" },
      { key: "shower_rm_install", label_ar: "فك وتركيب كابينة شاور", unit_ar: "وحدة" },
    ],
  },
  "الوميتال": {
    items: [
      { key: "metal_door", label_ar: "باب وميتال", unit_ar: "باب" },
      { key: "metal_facade", label_ar: "واجهة وميتال", unit_ar: "متر²" },
      { key: "garage_door", label_ar: "باب جراج وميتال", unit_ar: "وحدة" },
      { key: "metal_window", label_ar: "شباك ألوميتال", unit_ar: "شباك" },
      { key: "balcony_door", label_ar: "باب بلكونة ألوميتال", unit_ar: "باب" },
      { key: "bath_door", label_ar: "باب حمام ألوميتال", unit_ar: "باب" },
      { key: "kitchen_door", label_ar: "باب مطبخ ألوميتال", unit_ar: "باب" },
      { key: "sliding_window", label_ar: "شباك جرار", unit_ar: "شباك" },
      { key: "hinged_window", label_ar: "شباك مفصلي", unit_ar: "شباك" },
      { key: "vertical_slide_window", label_ar: "شباك سحاب", unit_ar: "شباك" },
      { key: "fixed_window", label_ar: "شباك ثابت", unit_ar: "شباك" },
      { key: "sliding_door_alum", label_ar: "باب جرار ألوميتال", unit_ar: "باب" },
      { key: "folding_door_alum", label_ar: "باب سحاب ألوميتال", unit_ar: "باب" },
      { key: "window_install_alum", label_ar: "تركيب شباك ألوميتال", unit_ar: "شباك" },
      { key: "door_install_alum", label_ar: "تركيب باب ألوميتال", unit_ar: "باب" },
      { key: "remove_door_window", label_ar: "فك باب أو شباك ألوميتال", unit_ar: "قطعة" },
      { key: "old_window_replace", label_ar: "تغيير شباك قديم", unit_ar: "شباك" },
      { key: "store_facade", label_ar: "واجهة محل", unit_ar: "متر²" },
      { key: "office_facade", label_ar: "واجهة مكتب", unit_ar: "متر²" },
      { key: "company_facade", label_ar: "واجهة شركة", unit_ar: "متر²" },
      { key: "balcony_facade", label_ar: "واجهة بلكونة", unit_ar: "متر²" },
      { key: "alum_dividers", label_ar: "تقسيمات ألوميتال", unit_ar: "متر²" },
      { key: "alum_partitions", label_ar: "قواطع ألوميتال", unit_ar: "متر²" },
      { key: "partition_install_alum", label_ar: "تركيب قواطع ألوميتال", unit_ar: "متر²" },
      { key: "sliding_garage", label_ar: "باب جراج جرار", unit_ar: "باب" },
      { key: "hinged_garage", label_ar: "باب جراج مفصلي", unit_ar: "باب" },
      { key: "garage_install", label_ar: "تركيب باب جراج", unit_ar: "باب" },
      { key: "garage_repair", label_ar: "إصلاح باب جراج", unit_ar: "باب" },
      { key: "garage_wheels_change", label_ar: "تغيير عجلات باب الجراج", unit_ar: "قطعة" },
      { key: "alum_hinges_change", label_ar: "تغيير مفصلات", unit_ar: "مفصل" },
      { key: "alum_lock_change", label_ar: "تغيير كالون", unit_ar: "قطعة" },
      { key: "alum_accs_change", label_ar: "تغيير إكسسوارات الباب", unit_ar: "قطعة" },
      { key: "alum_glass_change", label_ar: "تغيير زجاج ألوميتال", unit_ar: "متر²" },
      { key: "mosquito_mesh_change", label_ar: "تغيير سلك ناموسية", unit_ar: "متر²" },
      { key: "mosquito_net_install", label_ar: "تركيب ناموسية", unit_ar: "متر²" },
      { key: "roller_change", label_ar: "تغيير بكر الشباك", unit_ar: "قطعة" },
      { key: "roller_accs_change", label_ar: "تغيير إكسسوارات", unit_ar: "قطعة" },
      { key: "alum_hinges_repair", label_ar: "إصلاح مفصلات", unit_ar: "مفصل" },
      { key: "alum_lock_repair", label_ar: "إصلاح كالون", unit_ar: "قطعة" },
      { key: "door_window_adjust", label_ar: "ضبط باب أو شباك", unit_ar: "قطعة" },
      { key: "air_leak_fix", label_ar: "إصلاح تسريب الهواء", unit_ar: "قطعة" },
      { key: "alum_rm_install", label_ar: "فك وتركيب ألوميتال", unit_ar: "قطعة" },
    ],
  },
  "نقل اثاث": {
    items: [
      { key: "floor_lift", label_ar: "رفع أو نزول الأثاث بالدور", unit_ar: "دور" },
      { key: "truck_trip", label_ar: "عربية نقل داخل المدينة", unit_ar: "رحلة" },
      { key: "room_reassemble", label_ar: "فك وتركيب غرفة نوم أو بدروم", unit_ar: "غرفة" },
      { key: "move_in_city", label_ar: "نقل أثاث داخل المدينة", unit_ar: "رحلة" },
      { key: "move_out_city", label_ar: "نقل أثاث خارج المدينة", unit_ar: "رحلة" },
      { key: "move_full_apartment", label_ar: "نقل شقة كاملة", unit_ar: "شقة" },
      { key: "move_room", label_ar: "نقل غرفة", unit_ar: "غرفة" },
      { key: "move_office", label_ar: "نقل مكتب", unit_ar: "مكتب" },
      { key: "move_shop", label_ar: "نقل محل", unit_ar: "محل" },
      { key: "move_household", label_ar: "نقل أجهزة منزلية", unit_ar: "قطعة" },
      { key: "move_household_goods", label_ar: "نقل عفش", unit_ar: "شقة" },
      { key: "move_single_piece", label_ar: "نقل قطع أثاث منفردة", unit_ar: "قطعة" },
      { key: "move_fridge", label_ar: "نقل ثلاجة", unit_ar: "قطعة" },
      { key: "move_washing", label_ar: "نقل غسالة", unit_ar: "قطعة" },
      { key: "move_stove", label_ar: "نقل بوتاجاز", unit_ar: "قطعة" },
      { key: "move_ac", label_ar: "نقل تكييف", unit_ar: "وحدة" },
      { key: "move_tv", label_ar: "نقل تلفزيون", unit_ar: "قطعة" },
      { key: "move_office_furniture", label_ar: "نقل أثاث مكتبي", unit_ar: "مكتب" },
      { key: "lift_up", label_ar: "رفع أثاث بالدور", unit_ar: "دور" },
      { key: "lift_down", label_ar: "تنزيل أثاث بالدور", unit_ar: "دور" },
      { key: "lift_up_crane", label_ar: "رفع أثاث بالونش", unit_ar: "دور" },
      { key: "lift_down_crane", label_ar: "تنزيل أثاث بالونش", unit_ar: "دور" },
      { key: "move_by_stairs", label_ar: "نقل أثاث بالسلم", unit_ar: "دور" },
      { key: "loading_furniture", label_ar: "تحميل أثاث", unit_ar: "ساعة" },
      { key: "unloading_furniture", label_ar: "تنزيل أثاث", unit_ar: "ساعة" },
      { key: "loading_workers", label_ar: "عمال تحميل وتنزيل", unit_ar: "عامل" },
      { key: "extra_mover", label_ar: "عامل نقل أثاث إضافي", unit_ar: "عامل" },
      { key: "small_truck", label_ar: "عربية نقل صغيرة", unit_ar: "رحلة" },
      { key: "big_truck", label_ar: "عربية نقل كبيرة", unit_ar: "رحلة" },
      { key: "half_load", label_ar: "نصف نقل", unit_ar: "رحلة" },
      { key: "move_with_workers", label_ar: "نقل بعمالة", unit_ar: "رحلة" },
      { key: "move_no_workers", label_ar: "نقل بدون عمالة", unit_ar: "رحلة" },
      { key: "truck_hourly", label_ar: "تأجير عربية بالساعة", unit_ar: "ساعة" },
      { key: "truck_daily", label_ar: "تأجير عربية باليوم", unit_ar: "يوم" },
      { key: "bedroom_remove", label_ar: "فك غرفة نوم", unit_ar: "غرفة" },
      { key: "bedroom_install", label_ar: "تركيب غرفة نوم", unit_ar: "غرفة" },
      { key: "wardrobe_remove", label_ar: "فك دولاب", unit_ar: "قطعة" },
      { key: "wardrobe_install_n", label_ar: "تركيب دولاب", unit_ar: "قطعة" },
      { key: "kitchen_remove_n", label_ar: "فك مطبخ", unit_ar: "متر طولي" },
      { key: "kitchen_install_n2", label_ar: "تركيب مطبخ", unit_ar: "متر طولي" },
      { key: "bed_remove", label_ar: "فك سرير", unit_ar: "قطعة" },
      { key: "bed_install", label_ar: "تركيب سرير", unit_ar: "قطعة" },
      { key: "desk_remove", label_ar: "فك مكتب", unit_ar: "قطعة" },
      { key: "desk_install", label_ar: "تركيب مكتب", unit_ar: "قطعة" },
      { key: "sofa_remove", label_ar: "فك كنبة", unit_ar: "قطعة" },
      { key: "sofa_install", label_ar: "تركيب كنبة", unit_ar: "قطعة" },
      { key: "full_rm_install", label_ar: "فك وتركيب أثاث كامل", unit_ar: "شقة" },
      { key: "badroom_rm_install", label_ar: "فك وتركيب بدروم", unit_ar: "غرفة" },
      { key: "pack_prior", label_ar: "تغليف الأثاث قبل النقل", unit_ar: "قطعة" },
      { key: "unplug_prior", label_ar: "فك الأجهزة قبل النقل", unit_ar: "قطعة" },
      { key: "plug_after", label_ar: "تركيب الأجهزة بعد النقل", unit_ar: "قطعة" },
    ],
  },
  "ونش تشوين": {
    items: [
      { key: "material_floor", label_ar: "رفع مواد بناء بالدور", unit_ar: "دور" },
      { key: "crane_day", label_ar: "تأجير ونش بيومه مع السائق", unit_ar: "يوم" },
      { key: "lift_sand", label_ar: "رفع رمل", unit_ar: "متر³" },
      { key: "lift_cement", label_ar: "رفع أسمنت", unit_ar: "طن" },
      { key: "lift_brick", label_ar: "رفع طوب", unit_ar: "ألف" },
      { key: "lift_block", label_ar: "رفع بلوك", unit_ar: "متر²" },
      { key: "lift_tiles", label_ar: "رفع سيراميك", unit_ar: "متر²" },
      { key: "lift_marble", label_ar: "رفع رخام", unit_ar: "متر²" },
      { key: "lift_gb", label_ar: "رفع جبس بورد", unit_ar: "لوح" },
      { key: "lift_gypsum", label_ar: "رفع جبس", unit_ar: "كيس" },
      { key: "lift_wood", label_ar: "رفع أخشاب", unit_ar: "متر³" },
      { key: "lift_iron", label_ar: "رفع حديد", unit_ar: "طن" },
      { key: "lift_pipes", label_ar: "رفع مواسير", unit_ar: "متر" },
      { key: "lift_furniture", label_ar: "رفع أثاث", unit_ar: "قطعة" },
      { key: "lift_appliances", label_ar: "رفع أجهزة منزلية", unit_ar: "قطعة" },
      { key: "lift_debris", label_ar: "رفع مخلفات البناء", unit_ar: "متر³" },
      { key: "lower_materials", label_ar: "تنزيل مواد من الأدوار", unit_ar: "دور" },
      { key: "lower_debris", label_ar: "تنزيل مخلفات البناء", unit_ar: "متر³" },
      { key: "crane_hourly", label_ar: "تأجير ونش بالساعة", unit_ar: "ساعة" },
      { key: "crane_weekly", label_ar: "تأجير ونش بالأسبوع", unit_ar: "أسبوع" },
      { key: "in_site_transfer", label_ar: "نقل/تشوين مواد داخل الموقع", unit_ar: "ساعة" },
    ],
  },
  "تركيب كرانيش فوم": {
    items: [
      { key: "foam_cornice", label_ar: "كورنيش فوم (تركيب)", unit_ar: "متر طولي" },
      { key: "foam_rosette", label_ar: "روزيت أو زخرفة فوم", unit_ar: "قطعة" },
      { key: "wall_panel", label_ar: "بانل حوائط فوم/PVC", unit_ar: "متر²" },
      { key: "ceiling_cornice_fit", label_ar: "تركيب كرانيش فوم للأسقف", unit_ar: "متر طولي" },
      { key: "wall_cornice_fit", label_ar: "تركيب كرانيش فوم للحائط", unit_ar: "متر طولي" },
      { key: "rosette_fit", label_ar: "تركيب روزيت فوم", unit_ar: "قطعة" },
      { key: "decor_fit", label_ar: "تركيب زخارف فوم", unit_ar: "قطعة" },
      { key: "columns_fit", label_ar: "تركيب أعمدة فوم ديكورية", unit_ar: "قطعة" },
      { key: "frames_fit", label_ar: "تركيب إطارات فوم للحائط", unit_ar: "قطعة" },
      { key: "profile_fit", label_ar: "تركيب بروفايل فوم", unit_ar: "متر طولي" },
      { key: "dividers_fit", label_ar: "تركيب فواصل فوم", unit_ar: "متر طولي" },
      { key: "panels_fit", label_ar: "تركيب بانوهات فوم", unit_ar: "قطعة" },
      { key: "wood_alt_fit", label_ar: "تركيب بديل الخشب فوم", unit_ar: "متر²" },
      { key: "marble_alt_fit", label_ar: "تركيب بديل الرخام PVC", unit_ar: "متر²" },
      { key: "pvc_boards_fit", label_ar: "تركيب ألواح PVC", unit_ar: "متر²" },
      { key: "pvc_panel_fit", label_ar: "تركيب باندل حوائط PVC", unit_ar: "متر²" },
      { key: "remove_old_cornice", label_ar: "فك كرانيش فوم قديمة", unit_ar: "متر طولي" },
      { key: "fix_cornice", label_ar: "إصلاح كرانيش فوم", unit_ar: "متر طولي" },
      { key: "paint_cornice", label_ar: "دهان كرانيش وزخارف الفوم", unit_ar: "متر طولي" },
      { key: "joins_finish", label_ar: "تشطيب ومعالجة فواصل الفوم", unit_ar: "متر طولي" },
    ],
  },
  "صيانة دش": {
    items: [
      { key: "dish_install", label_ar: "تركيب طبق دش", unit_ar: "وحدة" },
      { key: "dish_service", label_ar: "ضبط أو صيانة دش", unit_ar: "زيارة" },
      { key: "cable_meter", label_ar: "كابل", unit_ar: "متر" },
      { key: "new_dish_install", label_ar: "تركيب طبق دش جديد", unit_ar: "وحدة" },
      { key: "rm_install_dish", label_ar: "فك وتركيب طبق دش", unit_ar: "وحدة" },
      { key: "signal_align", label_ar: "ضبط إشارة الطبق", unit_ar: "زيارة" },
      { key: "lnb_change", label_ar: "تغيير LNB", unit_ar: "قطعة" },
      { key: "lnb_install", label_ar: "تركيب LNB", unit_ar: "قطعة" },
      { key: "cable_connection_change", label_ar: "تغيير وصلة دش", unit_ar: "قطعة" },
      { key: "cable_repair", label_ar: "إصلاح كابل الدش", unit_ar: "متر" },
      { key: "cable_extend", label_ar: "تمديد كابل دش", unit_ar: "متر" },
      { key: "new_cable_install", label_ar: "تركيب كابل دش جديد", unit_ar: "متر" },
      { key: "splitter_install", label_ar: "تركيب سبليتر دش", unit_ar: "قطعة" },
      { key: "dish_switch_install", label_ar: "تركيب مفتاح دش", unit_ar: "قطعة" },
      { key: "weak_signal_fix", label_ar: "إصلاح ضعف الإشارة", unit_ar: "زيارة" },
      { key: "channels_align", label_ar: "ضبط القنوات", unit_ar: "زيارة" },
      { key: "receiver_program", label_ar: "برمجة الرسيفر", unit_ar: "جهاز" },
      { key: "receiver_install", label_ar: "تركيب رسيفر", unit_ar: "جهاز" },
      { key: "receiver_setup", label_ar: "إعداد رسيفر", unit_ar: "جهاز" },
      { key: "dish_move", label_ar: "نقل طبق الدش", unit_ar: "وحدة" },
      { key: "dish_relocate", label_ar: "تغيير مكان الطبق", unit_ar: "وحدة" },
      { key: "dish_mount_fix", label_ar: "تثبيت حامل الطبق", unit_ar: "وحدة" },
      { key: "motor_service", label_ar: "صيانة موتور الطبق", unit_ar: "زيارة" },
      { key: "dish_motor_install", label_ar: "تركيب موتور دش", unit_ar: "قطعة" },
    ],
  },
  "مكافحة حشرات وقوارض": {
    items: [
      { key: "full_apartment", label_ar: "رش شقة كاملة", unit_ar: "شقة" },
      { key: "single_room", label_ar: "رش غرفة واحدة", unit_ar: "غرفة" },
      { key: "follow_up_visit", label_ar: "زيارة متابعة", unit_ar: "زيارة" },
      { key: "roach_spray", label_ar: "رش صراصير", unit_ar: "غرفة" },
      { key: "ant_spray", label_ar: "رش نمل", unit_ar: "غرفة" },
      { key: "bedbug_spray", label_ar: "رش بق الفراش", unit_ar: "غرفة" },
      { key: "bedbug_control", label_ar: "مكافحة البق", unit_ar: "غرفة" },
      { key: "fly_control", label_ar: "مكافحة الذباب", unit_ar: "غرفة" },
      { key: "mosquito_control", label_ar: "مكافحة الناموس", unit_ar: "غرفة" },
      { key: "flea_control", label_ar: "مكافحة البراغيث", unit_ar: "غرفة" },
      { key: "moth_control", label_ar: "مكافحة العته", unit_ar: "غرفة" },
      { key: "crawling_pest", label_ar: "مكافحة الحشرات الزاحفة", unit_ar: "غرفة" },
      { key: "flying_pest", label_ar: "مكافحة الحشرات الطائرة", unit_ar: "غرفة" },
      { key: "mice_control", label_ar: "مكافحة الفئران", unit_ar: "شغلانة" },
      { key: "rat_control", label_ar: "مكافحة الجرذان", unit_ar: "شغلانة" },
      { key: "rodent_control", label_ar: "مكافحة القوارض", unit_ar: "شغلانة" },
      { key: "rodent_baits", label_ar: "وضع طعوم للقوارض", unit_ar: "شغلانة" },
      { key: "rodent_traps", label_ar: "تركيب مصائد للقوارض", unit_ar: "قطعة" },
      { key: "termites_control", label_ar: "مكافحة النمل الأبيض", unit_ar: "متر²" },
      { key: "kitchen_spray", label_ar: "رش مطبخ", unit_ar: "غرفة" },
      { key: "bath_spray", label_ar: "رش حمام", unit_ar: "غرفة" },
      { key: "roof_spray", label_ar: "رش سطح", unit_ar: "متر²" },
      { key: "hall_spray", label_ar: "رش مدخل/سلم", unit_ar: "دور" },
      { key: "shop_spray", label_ar: "رش محل", unit_ar: "محل" },
      { key: "office_spray", label_ar: "رش مكتب", unit_ar: "مكتب" },
      { key: "warehouse_spray", label_ar: "رش مخزن", unit_ar: "مخزن" },
      { key: "restaurant_spray", label_ar: "رش مطعم", unit_ar: "مطعم" },
      { key: "villa_spray", label_ar: "رش فيلا", unit_ar: "فيلا" },
      { key: "building_spray", label_ar: "رش عمارة كاملة", unit_ar: "عمارة" },
      { key: "inspect_visit", label_ar: "زيارة كشف ومعاينة", unit_ar: "زيارة" },
      { key: "second_follow_up", label_ar: "زيارة متابعة ثانية", unit_ar: "زيارة" },
      { key: "post_sterilize", label_ar: "تعقيم بعد المكافحة", unit_ar: "متر²" },
    ],
  },
  "حمامات سباحة": {
    items: [
      { key: "pool_build_m3", label_ar: "إنشاء حوض مسباح", unit_ar: "متر³" },
      { key: "pool_waterproofing", label_ar: "عزل وتلبيس المسباح", unit_ar: "متر²" },
      { key: "pump_install", label_ar: "تركيب فلتر أو مضخة", unit_ar: "وحدة" },
      { key: "pool_tile_repair", label_ar: "إصلاح وتغيير بلاط المسباح", unit_ar: "متر²" },
      { key: "pool_tile_grout", label_ar: "حقن العراميس ودهان المسباح", unit_ar: "متر²" },
      { key: "pool_floor_levelling", label_ar: "تسوية أرضية المسباح", unit_ar: "متر²" },
      { key: "pool_leak_search", label_ar: "كشف تسريب المسباح", unit_ar: "شغلانة" },
      { key: "pool_leak_repair", label_ar: "إصلاح تسريب المسباح", unit_ar: "شغلانة" },
      { key: "pool_cleaning", label_ar: "تنظيف عام للمسباح", unit_ar: "مسباح" },
      { key: "pool_skimmer_clean", label_ar: "تنظيف سطح المسباح بالاسكيمر", unit_ar: "مسباح" },
      { key: "pool_wall_brush", label_ar: "فرك حوائط المسباح", unit_ar: "مسباح" },
      { key: "pool_floor_vacuum", label_ar: "شفط أرضية المسباح", unit_ar: "مسباح" },
      { key: "pool_backwash", label_ar: "غسيل عكسي للفلتر", unit_ar: "مرة" },
      { key: "pool_filter_clean", label_ar: "تنظيف الفلتر", unit_ar: "قطعة" },
      { key: "pool_sand_change", label_ar: "تغيير رمل الفلتر", unit_ar: "مرة" },
      { key: "pool_cartridge_change", label_ar: "تغيير كرتونة الفلتر", unit_ar: "قطعة" },
      { key: "pool_pump_repair", label_ar: "إصلاح مضخة المسباح", unit_ar: "قطعة" },
      { key: "pool_pump_replacement", label_ar: "تغيير مضخة المسباح", unit_ar: "قطعة" },
      { key: "pool_motor_repair", label_ar: "إصلاح موتور المسباح", unit_ar: "قطعة" },
      { key: "pool_motor_replacement", label_ar: "تغيير موتور المسباح", unit_ar: "قطعة" },
      { key: "pool_pipe_repair", label_ar: "إصلاح مواسير المسباح", unit_ar: "متر" },
      { key: "pool_hose_replace", label_ar: "تغيير خراطيم المسباح", unit_ar: "متر" },
      { key: "pool_chemical_balance", label_ar: "ضبط كيمياء مياه المسباح", unit_ar: "مرة" },
      { key: "pool_chlorine_add", label_ar: "إضافة كلور ومطهرات", unit_ar: "مرة" },
      { key: "pool_light_install", label_ar: "تركيب أو إصلاح إضاءة المسباح", unit_ar: "قطعة" },
      { key: "pool_heater_install", label_ar: "تركيب سخان مسباح", unit_ar: "قطعة" },
      { key: "pool_heater_repair", label_ar: "إصلاح سخان المسباح", unit_ar: "قطعة" },
      { key: "pool_cover_install", label_ar: "تركيب غطاء مسباح", unit_ar: "قطعة" },
      { key: "pool_safety_net", label_ar: "تركيب شبكة أمان للمسباح", unit_ar: "متر²" },
      { key: "pool_drain_install", label_ar: "تركيب مصفاة وطرد المسباح", unit_ar: "قطعة" },
      { key: "pool_full_maintenance", label_ar: "صيانة دورية شاملة للمسباح", unit_ar: "شهر" },
    ],
  },
  "صيانة اجهزة منزلية": {
    items: [
      { key: "visit_fee", label_ar: "زيارة كشف وصيانة", unit_ar: "زيارة" },
      { key: "work_hour", label_ar: "ساعة عمل", unit_ar: "ساعة" },
      { key: "appliance_install", label_ar: "تركيب جهاز (غسالة، طباخ، نشافة...)", unit_ar: "وحدة" },
      { key: "appl_washing_repair", label_ar: "إصلاح غسالة ملابس", unit_ar: "جهاز" },
      { key: "appl_dryer_repair", label_ar: "إصلاح نشافة ملابس", unit_ar: "جهاز" },
      { key: "appl_dishwasher_repair", label_ar: "إصلاح غسالة أطباق", unit_ar: "جهاز" },
      { key: "appl_fridge_repair", label_ar: "إصلاح ثلاجة", unit_ar: "جهاز" },
      { key: "appl_fridge_defrost", label_ar: "فك ونزع ثلج الفريزر", unit_ar: "مرة" },
      { key: "appl_freezer_repair", label_ar: "إصلاح فريزر", unit_ar: "جهاز" },
      { key: "appl_oven_repair", label_ar: "إصلاح فرن", unit_ar: "جهاز" },
      { key: "appl_cooker_repair", label_ar: "إصلاح طباخ/بوتاجاز", unit_ar: "جهاز" },
      { key: "appl_microwave_repair", label_ar: "إصلاح ميكروويف", unit_ar: "جهاز" },
      { key: "appl_water_heater", label_ar: "إصلاح سخان كهربائي", unit_ar: "جهاز" },
      { key: "appl_vacuum_repair", label_ar: "إصلاح مكنسة كهربائية", unit_ar: "جهاز" },
      { key: "appl_iron_repair", label_ar: "إصلاح مكواة", unit_ar: "جهاز" },
      { key: "appl_fan_repair", label_ar: "إصلاح مروحة", unit_ar: "جهاز" },
      { key: "appl_exhaust_repair", label_ar: "إصلاح شفاط مطبخ", unit_ar: "جهاز" },
      { key: "appl_heater_repair", label_ar: "إصلاح دفاية", unit_ar: "جهاز" },
      { key: "appl_blender_repair", label_ar: "إصلاح خلاط أو عجان", unit_ar: "جهاز" },
      { key: "appl_motor_change", label_ar: "تغيير موتور الجهاز", unit_ar: "جهاز" },
      { key: "appl_compressor_change", label_ar: "تغيير كمبروسر الثلاجة", unit_ar: "قطعة" },
      { key: "appl_heater_element", label_ar: "تغيير عنصر التسخين", unit_ar: "قطعة" },
      { key: "appl_thermostat_change", label_ar: "تغيير ترموستات الجهاز", unit_ar: "قطعة" },
      { key: "appl_gas_valve", label_ar: "تغيير صمامات وخراطيم الغاز", unit_ar: "قطعة" },
      { key: "appl_belt_change", label_ar: "تغيير سير الغسالة", unit_ar: "قطعة" },
      { key: "appl_door_seal", label_ar: "تغيير كاوتش باب الغسالة", unit_ar: "قطعة" },
      { key: "appl_bearing_change", label_ar: "تغيير بريال الغسالة", unit_ar: "قطعة" },
      { key: "appl_drain_pump", label_ar: "تغيير طلمبة صرف الغسالة", unit_ar: "قطعة" },
      { key: "appl_pcb_repair", label_ar: "إصلاح أو تغيير بوردة الجهاز", unit_ar: "قطعة" },
      { key: "appl_full_service", label_ar: "صيانة شاملة وتنظيف الجهاز", unit_ar: "جهاز" },
    ],
  },
};

function getSchemaByCategoryName(nameAr) {
  if (!nameAr) return null;
  return PRICING_SCHEMAS[String(nameAr).trim()] || null;
}

module.exports = { PRICING_SCHEMAS, getSchemaByCategoryName };
